JS scripts
Blockenzyme/recruitment_application pull request #30
Opened 2023-04-29 21:26 UTC by ayush-raj13

Dummy data for given no. of rows in all models can be generated using applicant.bat and recruiter.bat

2023-04-30 16:18 UTC, kole-swapnil requested changes

2023-04-30 16:18 UTC, kole-swapnil commented on javascripts/applicantDummyData.js
> +/* eslint-disable */
remove

2023-04-30 16:18 UTC, kole-swapnil commented on javascripts/applicantDummyData.js
> +    withCredentials: true, // If true, send cookie stored in jar
no proper indentation

2023-04-30 16:18 UTC, kole-swapnil commented on javascripts/applicantDummyData.js
> +
make new file javascripts/constants.js
put all these arrays in there.
=> export const collegeList

2023-04-30 16:18 UTC, kole-swapnil commented on javascripts/recruiterDummyData.js
> +
remove

2023-04-30 16:18 UTC, kole-swapnil commented on javascripts/recruiterDummyData.js
> +  const ats_list = [
move to constants

2023-04-30 17:54 UTC, ayush-raj13 commented on javascripts/applicantDummyData.js
> +/* eslint-disable */
done

2023-04-30 17:56 UTC, ayush-raj13 commented on javascripts/applicantDummyData.js
> +    withCredentials: true, // If true, send cookie stored in jar
formatted through eslint

2023-04-30 17:56 UTC, ayush-raj13 commented on javascripts/applicantDummyData.js
> +
done

2023-04-30 17:56 UTC, ayush-raj13 commented on javascripts/recruiterDummyData.js
> +
done

2023-04-30 17:57 UTC, ayush-raj13 commented on javascripts/recruiterDummyData.js
> +  const ats_list = [
done

2023-05-01 06:07 UTC, kole-swapnil requested changes

2023-05-01 06:07 UTC, kole-swapnil commented on javascripts/applicantDummyData.js
> +  console.log(res.data);
pls remove all eslint 
use debug.log

2023-05-01 06:07 UTC, kole-swapnil commented on javascripts/applicantDummyData.js
> +async function sequentialCall() {
same as before

2023-05-01 06:07 UTC, kole-swapnil commented on javascripts/applicantDummyData.js
> +  console.log(res.data);
*eslint-disable

2023-05-01 15:44 UTC, ayush-raj13 commented on javascripts/applicantDummyData.js
> +async function sequentialCall() {
done

2023-05-01 15:44 UTC, ayush-raj13 commented on javascripts/applicantDummyData.js
> +  console.log(res.data);
done

2023-05-25 08:19 UTC, kole-swapnil approved these changes

2023-05-25 09:19 UTC, Srutip04 approved these changes

2023-05-25 09:19 UTC, merged